#!/usr/bin/env bash
# Author: Alexis Moins
# Creation: 29 oct 2021
# vim: fdm=marker

# Files and dir to create first
init=( 
    ".vim/.cache/undo" 
    ".zsh/.cache/completion" 
    "${HOME}/.ssh" )

# Files and dir that will be exported to ~
included=( 
    ".gitconfig"
    ".ssh/config"
    ".tmux.conf"
    ".vim"
    ".zsh"
    ".zshenv" )

# +-- Functions

# 
function init-config {
    for item in "${init[@]}"; do
        [[ ! -d "${item}" ]] && \mkdir -pv "${item}"
    done

    [[ -d "${HOME}/.vim/.cache/undo" ]] && find "${HOME}/.vim/.cache/undo" -type f -mtime +30 -delete -print
}

function install-config {
    echo "Installing config"
    for item in "${included[@]}"; do
        if [[ -e "${item}" ]]; then
            \cp -Ri "${item}" "${HOME}"
            echo "-> ${item}"
        fi
    done
}

function fetch-config {
    echo "Fetching config"
    for item in "${included[@]}"; do
        if [[ -e "${HOME}/${item}" ]]; then
            \cp -R "${HOME}/${item}" .
            echo "-> ${item}"
        fi
    done
}

# --+

# 
init-config

# Fetch user config from home dir
[[ "${1}" = "fetch" ]] && fetch-config

# Copy config to the home dir
[[ "${1}" = "install" ]] && install-config

# Cleans the environment
unset init included

