#!/bin/zsh
# Author: Alexis Moins
# Creation: 01 aug 2021

# Where the zsh config is located
DOTFILES="${0:h:P}"

# Files and directories that must be ignored
ignored=( ".git" ".gitignore" "install" )

# Directories needed in order for vim to work correctly
[[ ! -d "${DOTFILES}/.vim/.undo" ]] && mkdir -v "${DOTFILES}/.vim/.undo"

# Directories needed in order for zsh to work correctly
[[ ! -d "${DOTFILES}/.zsh/cache" ]] && mkdir -pv "${DOTFILES}/.zsh/cache/completion"

# Links all files and directories
for link in "${DOTFILES}/"*(D); do
    [[ -z "${ignored[(r)${link:t}]}" ]] && ln -fnsv "${link}" "${HOME}/${link:t}"; done

# Removes the unnecessary variables
unset DOTFILES ignored
