" User configuration for vim
" Author: Alexis Moins
" Creation: 18 juin 2020

" Detects filetype, plugin and indentation
filetype plugin indent on

" Enables syntax coloration
syntax enable

" Load colorscheme depths
colorscheme test

" {{{ Plugins

call plug#begin('~/.vim/bundle')

" Delete / change add parentheses or quotes with ease
Plug 'tpope/vim-surround'

" Comment stuff out
Plug 'tpope/vim-commentary'

" 
Plug 'tpope/vim-projectionist'

" Make your Vim/Neovim as smart as VSCode
Plug 'neoclide/coc.nvim', { 'branch': 'release' }

call plug#end()

" List of coc extensions installed at first startup
let g:coc_global_extensions = [ 
            \ 'coc-pairs', 
            \ 'coc-clangd'
            \ ]

" coc-java

" }}}

" {{{ Netrw

" Cache la bannière
let g:netrw_banner=0
"
" Ouvre les splits à droite
let g:netrw_altv=1

" Tree view
let g:netrw_liststyle=3

" Sequence for sorting by name
let g:netrw_sort_sequence='[\/]$,*'

" Where to save the history file
let g:netrw_home="${VIMDOTDIR}/.cache/netrwhist"

" }}}

" {{{ Options

set modelines=5

" Time before CursorHold events are triggered
set updatetime=100

set wildmenu  

" Display line numbers
set number

" Display signs over the line number
set signcolumn=number

" Automatically replace tabulations with spaces
set expandtab

" One tab equals 4 spaces
set tabstop=4

" Use 4 spaces for indentation
set shiftwidth=4

" Keep the indentation of the last line
set autoindent

" Change buffers without having to save them
set hidden

" Reload files modified from outside of vim
set autoread

" Ignore the case during search
set ignorecase

" Override 'ignorecase' if the search pattern contains upper case characters
set smartcase

" Display match during search
set incsearch

" Never wrap lines when they are too long
set nowrap  

" Always display the next 8 lines below or above the cursor 
set scrolloff=5

" Never pass beyond 120 characters on a line
set textwidth=120

" Open vertical splits to the right
set splitright

" Open horizontal splits below
set splitbelow

" Set the content of the statusline
set statusline=%2*\ %t\ %0*[.]\ %3*%m%4*%=\ \ %5*%y\ 

" Always display the statusline
set laststatus=2

" Use markers to create folds
set foldmethod=marker

" Only fold 1 time
set foldnestmax=1

" Use the patience algorithm to show differences, don't take whitespaces into
" account and completely fold identical parts
set diffopt+=iwhiteall,context:0

" Highlight the text line of the cursor
set cursorline

" Add French to the known languages for spellcheck
set spelllang+=fr

" Location of the system dictionary
set dictionary=/usr/share/dict/words

" Don't add anything at the end of the folded line
set fillchars=fold:\ 

"
set listchars=eol:¬,extends:>,precedes:<,tab:>\ 

" During search, look inside of the current directory and subdirectories
set path=.,**

" Expected behaviour of the backspace key
set backspace=start,eol,indent

" Location of the .viminfo file
set viminfofile=${VIMDOTDIR}/.cache/viminfo

" Never use swapfiles
set noswapfile

" Save the undotree for each file in the .undo directory
set undofile

" Location of the .undo directory
set undodir=${VIMDOTDIR}/.cache/undo

"
set shortmess+=Ic

" Enables mouse usage in all modes
set mouse=a

" Don't save useless session information
set sessionoptions-=blank sessionoptions-=options sessionoptions-=tabpages

" }}}
