set -gx GUM_FILTER_MATCH_FOREGROUND  "2"
set -gx GUM_FILTER_PROMPT_FOREGROUND "7"
set -gx GUM_FILTER_INDICATOR_FOREGROUND "1"

set -gx GUM_FILTER_SELECTED_PREFIX_FOREGROUND "4"
set -gx GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND "#6e738d"

set -gx GUM_FILTER_INDICATOR ">"
