[env]
term = "xterm-256color"

[general]
import = ["themes/rose-pine-moon.toml"]

# [terminal.shell]
# program = "/usr/bin/fish"

[font]
size = 13.0

[font.offset]
x = 0
y = 1

[font.normal]
# family = "JetbrainsMono Nerd Font Mono"
family = "Zenbones Brainy Regular"

[font.bold]
family = "Zenbones Brainy Regular"
style = "Bold"

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "Block"
blinking = "On"

[window]
# decorations = "None"
title = "(°-°)"

[window.padding]
x = 5
y = 0

[window.dimensions]
columns = 140
lines = 35
