-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "blossom-chad"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { fg = "#976153" })
hi(0, "@attribute", { fg = "#738199" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@boolean", { fg = "#ae81ff" })
hi(0, "@character", { fg = "#8779a8" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment", { fg = "#b2aba8" })
hi(0, "@comment.danger", { bg = "#b28069", fg = "#d9d2cf" })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { bg = "#695d57", fg = "#d9d2cf" })
hi(0, "@comment.todo", { bg = "#695d57", fg = "#b9b2af" })
hi(0, "@comment.warning", { bg = "#a87678", fg = "#d9d2cf" })
hi(0, "@conditional.ternary", { fg = "#89ddff" })
hi(0, "@constant", { fg = "#8779a8" })
hi(0, "@constant.builtin", { fg = "#a87678" })
hi(0, "@constant.macro", { fg = "#8779a8" })
hi(0, "@constructor", { fg = "#5e908e" })
hi(0, "@constructor.tsx", { link = "Tag" })
hi(0, "@definition", { sp = "#cac3c0", underline = true })
hi(0, "@delimiter", { fg = "#da70ca" })
hi(0, "@diff.delta", { fg = "#a09996" })
hi(0, "@diff.minus", { fg = "#b28069" })
hi(0, "@diff.plus", { fg = "#6c805c" })
hi(0, "@error", { fg = "#8779a8" })
hi(0, "@function", { fg = "#b3816a" })
hi(0, "@function.builtin", { fg = "#b3816a" })
hi(0, "@function.call", { fg = "#b3816a" })
hi(0, "@function.macro", { fg = "#8779a8" })
hi(0, "@function.method", { fg = "#b3816a" })
hi(0, "@function.method.call", { fg = "#b3816a" })
hi(0, "@ibl.indent.char.1", { fg = "#d3ccc9", nocombine = true })
hi(0, "@ibl.scope.char.1", { fg = "#b9b2af", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#b9b2af", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = "#d1cac7" })
hi(0, "@keyword", { fg = "#7e8e8e" })
hi(0, "@keyword.conditional", { fg = "#7e8e8e" })
hi(0, "@keyword.conditional.ternary", { fg = "#7e8e8e" })
hi(0, "@keyword.directive", { fg = "#738199" })
hi(0, "@keyword.directive.define", { fg = "#7e8e8e" })
hi(0, "@keyword.exception", { fg = "#8779a8" })
hi(0, "@keyword.function", { fg = "#7e8e8e" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { fg = "#7e8e8e" })
hi(0, "@keyword.repeat", { fg = "#738199" })
hi(0, "@keyword.return", { fg = "#7e8e8e" })
hi(0, "@keyword.storage", { fg = "#738199" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading", { fg = "#b3816a" })
hi(0, "@markup.link", { fg = "#8779a8" })
hi(0, "@markup.link.label", { fg = "#5e908e" })
hi(0, "@markup.link.url", { fg = "#a87678", underline = true })
hi(0, "@markup.list", { fg = "#8779a8" })
hi(0, "@markup.quote", { bg = "#d9d2cf" })
hi(0, "@markup.raw", { fg = "#a87678" })
hi(0, "@module", { fg = "#8779a8" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@number", { fg = "#a87678" })
hi(0, "@number.float", { fg = "#a87678" })
hi(0, "@operator", { fg = "#746862" })
hi(0, "@parenthesis", { link = "@punctuation.bracket" })
hi(0, "@property", { fg = "#8779a8" })
hi(0, "@punctuation.bracket", { fg = "#976153" })
hi(0, "@punctuation.delimiter", { fg = "#976153" })
hi(0, "@punctuation.special", { fg = "#39adb5" })
hi(0, "@reference", { fg = "#746862" })
hi(0, "@scope", { bold = true })
hi(0, "@string", { fg = "#6c805c" })
hi(0, "@string.escape", { fg = "#5e908e" })
hi(0, "@string.regex", { fg = "#5e908e" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { fg = "#879a39" })
hi(0, "@symbol", { fg = "#6c805c" })
hi(0, "@tag", { fg = "#738199" })
hi(0, "@tag.attribute", { fg = "#8779a8" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#976153" })
hi(0, "@text", { fg = "#746862" })
hi(0, "@text.emphasis", { fg = "#a87678" })
hi(0, "@text.strike", { fg = "#976153", strikethrough = true })
hi(0, "@type.builtin", { fg = "#738199" })
hi(0, "@type.qualifier", { fg = "#89ddff" })
hi(0, "@uri", { fg = "#7fb4ca" })
hi(0, "@variable", { fg = "#746862" })
hi(0, "@variable.builtin", { fg = "#a87678" })
hi(0, "@variable.member", { fg = "#8779a8" })
hi(0, "@variable.member.key", { fg = "#8779a8" })
hi(0, "@variable.parameter", { fg = "#8779a8" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#a87678" })
hi(0, "Character", { fg = "#8779a8" })
hi(0, "CmpBorder", { fg = "#b2aba8" })
hi(0, "CmpDoc", { bg = "#dfd8d5" })
hi(0, "CmpDocBorder", { bg = "#dfd8d5", fg = "#dfd8d5" })
hi(0, "CmpItemAbbr", { fg = "#695d57" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#565c64" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#5f7d9b" })
hi(0, "CmpItemKindClass", { fg = "#4b6987" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCodeium", { fg = "#899d79" })
hi(0, "CmpItemKindColor", { fg = "#695d57" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#a87678" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#5f7d9b" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#6c805c" })
hi(0, "CmpItemKindDefault", { fg = "#56b6c2" })
hi(0, "CmpItemKindEnum", { fg = "#5f7d9b" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#a685a6" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#a9a29f" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#8779a8" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#695d57" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#695d57" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#b3816a" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindIdentifier", { fg = "#8779a8" })
hi(0, "CmpItemKindInterface", { fg = "#6c805c" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#695d57" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#b3816a" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#738199" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#746862" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#8779a8" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#746862" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#b28069" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#7e8e8e" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructure", { fg = "#7e8e8e" })
hi(0, "CmpItemKindTabNine", { fg = "#b7856e" })
hi(0, "CmpItemKindText", { fg = "#6c805c" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindType", { fg = "#738199" })
hi(0, "CmpItemKindTypeParameter", { fg = "#8779a8" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#7e8e8e" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#75998e" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#7e8e8e" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpPmenu", { bg = "#e6dfdc" })
hi(0, "CmpSel", { bg = "#857e7b", fg = "#e6dfdc" })
hi(0, "ColorColumn", { bg = "#d9d2cf" })
hi(0, "Comment", { fg = "#b2aba8" })
hi(0, "Conceal", {})
hi(0, "Conditional", { fg = "#7e8e8e" })
hi(0, "Constant", { fg = "#8779a8" })
hi(0, "Cursor", { bg = "#746862", fg = "#e6dfdc" })
hi(0, "CursorColumn", { bg = "#ded7d4" })
hi(0, "CursorLine", { bg = "#d9d2cf" })
hi(0, "CursorLineNr", { fg = "#695d57" })
hi(0, "Debug", { fg = "#8779a8" })
hi(0, "Define", { fg = "#7e8e8e" })
hi(0, "Delimiter", { fg = "#976153" })
hi(0, "DiagnosticError", { fg = "#b28069" })
hi(0, "DiagnosticHint", { fg = "#a685a6" })
hi(0, "DiagnosticInfo", { fg = "#6c805c" })
hi(0, "DiagnosticVirtualTextError", { bg = "#570f0e", fg = "#db302d" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#103a3c", fg = "#29a298" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#0f3856", fg = "#268bd3" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#332700", fg = "#b28500" })
hi(0, "DiagnosticWarn", { fg = "#a9a29f" })
hi(0, "DiffAdd", { fg = "#5f7d9b" })
hi(0, "DiffAdded", { fg = "#6c805c" })
hi(0, "DiffChange", { fg = "#a09996" })
hi(0, "DiffChangeDelete", { fg = "#b28069" })
hi(0, "DiffDelete", { fg = "#b28069" })
hi(0, "DiffModified", { fg = "#cc836c" })
hi(0, "DiffRemoved", { fg = "#b28069" })
hi(0, "DiffText", { bg = "#d9d2cf", fg = "#695d57" })
hi(0, "Directory", { fg = "#b3816a" })
hi(0, "Error", { bg = "#8779a8", fg = "#e6dfdc" })
hi(0, "ErrorMsg", { bg = "#e6dfdc", fg = "#8779a8" })
hi(0, "Exception", { fg = "#8779a8" })
hi(0, "Float", { fg = "#a87678" })
hi(0, "FloatBorder", { fg = "#5f7d9b" })
hi(0, "FoldColumn", { bg = "#ded7d4", fg = "#5e908e" })
hi(0, "Folded", { bg = "#d9d2cf", fg = "#a09996" })
hi(0, "Function", { fg = "#b3816a" })
hi(0, "GitSignsStagedAdd", { fg = "#597b60" })
hi(0, "GitSignsStagedAddLn", { fg = "#305777" })
hi(0, "GitSignsStagedAddNr", { fg = "#597b60" })
hi(0, "GitSignsStagedChange", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangeLn", { fg = "#37393d" })
hi(0, "GitSignsStagedChangeNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedelete", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#37393d" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedDelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7f605c" })
hi(0, "IblChar", { fg = "#d3ccc9" })
hi(0, "IblIndent", { link = "NonText" })
hi(0, "IblScope", { fg = "#42464e" })
hi(0, "IblScopeChar", { fg = "#b9b2af" })
hi(0, "IblWhitespace", { link = "NonText" })
hi(0, "Identifier", { fg = "#8779a8" })
hi(0, "IncSearch", { bg = "#a87678", fg = "#ded7d4" })
hi(0, "Include", { fg = "#b3816a" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#7e8e8e" })
hi(0, "Label", { fg = "#738199" })
hi(0, "LazyButton", { bg = "#d0c9c6", fg = "#b8b3b0" })
hi(0, "LazyCommit", { fg = "#6c805c" })
hi(0, "LazyCommitIssue", { fg = "#c18f78" })
hi(0, "LazyDir", { fg = "#746862" })
hi(0, "LazyH1", { bg = "#6c805c", fg = "#e6dfdc" })
hi(0, "LazyH2", { bold = true, fg = "#b28069", underline = true })
hi(0, "LazyNoCond", { fg = "#b28069" })
hi(0, "LazyOperator", { fg = "#695d57" })
hi(0, "LazyProgressDone", { fg = "#6c805c" })
hi(0, "LazyReasonCmd", { fg = "#d38a73" })
hi(0, "LazyReasonEvent", { fg = "#a9a29f" })
hi(0, "LazyReasonFt", { fg = "#a685a6" })
hi(0, "LazyReasonImport", { fg = "#695d57" })
hi(0, "LazyReasonKeys", { fg = "#4b6987" })
hi(0, "LazyReasonPlugin", { fg = "#b28069" })
hi(0, "LazyReasonRuntime", { fg = "#5e5f65" })
hi(0, "LazyReasonSource", { fg = "#75998e" })
hi(0, "LazyReasonStart", { fg = "#695d57" })
hi(0, "LazySpecial", { fg = "#5f7d9b" })
hi(0, "LazyTaskOutput", { fg = "#695d57" })
hi(0, "LazyUrl", { fg = "#746862" })
hi(0, "LazyValue", { fg = "#4b6987" })
hi(0, "LineNr", { fg = "#b9b2af" })
hi(0, "LspInlayHint", { bg = "#d9d1ce", fg = "#a09996" })
hi(0, "LspReferenceRead", { bg = "#695d57", fg = "#dfd8d5" })
hi(0, "LspReferenceText", { bg = "#695d57", fg = "#dfd8d5" })
hi(0, "LspReferenceWrite", { bg = "#695d57", fg = "#dfd8d5" })
hi(0, "LspSignatureActiveParameter", { bg = "#6c805c", fg = "#e6dfdc" })
hi(0, "Macro", { fg = "#8779a8" })
hi(0, "MasonHeader", { bg = "#b28069", fg = "#e6dfdc" })
hi(0, "MasonHeaderSecondary", { link = "MasonHighlightBlock" })
hi(0, "MasonHighlight", { fg = "#5f7d9b" })
hi(0, "MasonHighlightBlock", { bg = "#6c805c", fg = "#e6dfdc" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHighlightBlock" })
hi(0, "MasonMuted", { fg = "#a09996" })
hi(0, "MasonMutedBlock", { bg = "#d0c9c6", fg = "#a09996" })
hi(0, "MatchParen", { link = "MatchWord" })
hi(0, "MatchWord", { bg = "#b9b2af", fg = "#695d57" })
hi(0, "ModeMsg", { fg = "#6c805c" })
hi(0, "MoreMsg", { fg = "#6c805c" })
hi(0, "NonText", { fg = "#d1cac7" })
hi(0, "Normal", { bg = "#e6dfdc", fg = "#746862" })
hi(0, "NormalFloat", { bg = "#dfd8d5" })
hi(0, "Number", { fg = "#a87678" })
hi(0, "NvimInternalError", { fg = "#b28069" })
hi(0, "NvimTreeCursorLine", { bg = "#d9d2cf" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#746d6a" })
hi(0, "NvimTreeEndOfBuffer", { fg = "#dfd8d5" })
hi(0, "NvimTreeFolderArrowClosed", { fg = "#b2aba8" })
hi(0, "NvimTreeFolderArrowOpen", { fg = "#746d6a" })
hi(0, "NvimTreeFolderIcon", { fg = "#746d6a" })
hi(0, "NvimTreeFolderName", { fg = "#746d6a" })
hi(0, "NvimTreeGitDeleted", { fg = "#b28069" })
hi(0, "NvimTreeGitDirty", { fg = "#b28069" })
hi(0, "NvimTreeGitIgnored", { fg = "#a09996" })
hi(0, "NvimTreeGitNew", { fg = "#a9a29f" })
hi(0, "NvimTreeIndentMarker", { fg = "#c7c0bd" })
hi(0, "NvimTreeNormal", { bg = "#dfd8d5" })
hi(0, "NvimTreeNormalNC", { bg = "#dfd8d5" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#746d6a" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#b28069" })
hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#a9a29f" })
hi(0, "NvimTreeWinSeparator", { bg = "#dfd8d5", fg = "#dfd8d5" })
hi(0, "NvimTreeWindowPicker", { bg = "#d9d2cf", fg = "#b28069" })
hi(0, "Operator", { fg = "#746862" })
hi(0, "Pmenu", { bg = "#d0c9c6" })
hi(0, "PmenuSbar", { bg = "#d0c9c6" })
hi(0, "PmenuSel", { bg = "#857e7b", fg = "#e6dfdc" })
hi(0, "PmenuThumb", { bg = "#b9b2af" })
hi(0, "PreProc", { fg = "#738199" })
hi(0, "Question", { fg = "#b3816a" })
hi(0, "QuickFixLine", { bg = "#ded7d4" })
hi(0, "RenamerBorder", { fg = "#b28069" })
hi(0, "RenamerTitle", { bg = "#b28069", fg = "#e6dfdc" })
hi(0, "Repeat", { fg = "#738199" })
hi(0, "Search", { bg = "#738199", fg = "#ded7d4" })
hi(0, "SignColumn", { fg = "#d1cac7" })
hi(0, "Special", { fg = "#5e908e" })
hi(0, "SpecialChar", { fg = "#976153" })
hi(0, "SpecialKey", { fg = "#d1cac7" })
hi(0, "SpellBad", { sp = "#8779a8", undercurl = true })
hi(0, "SpellCap", { sp = "#b3816a", undercurl = true })
hi(0, "SpellLocal", { sp = "#5e908e", undercurl = true })
hi(0, "SpellRare", { sp = "#7e8e8e", undercurl = true })
hi(0, "St_CommandMode", { bg = "#6c805c", bold = true, fg = "#e6dfdc" })
hi(0, "St_CommandModeSep", { bg = "#b9b2af", fg = "#6c805c" })
hi(0, "St_ConfirmMode", { bg = "#4b6987", bold = true, fg = "#e6dfdc" })
hi(0, "St_ConfirmModeSep", { bg = "#b9b2af", fg = "#4b6987" })
hi(0, "St_EmptySpace", { bg = "#cdc6c3", fg = "#b9b2af" })
hi(0, "St_InsertMode", { bg = "#9c7b9c", bold = true, fg = "#e6dfdc" })
hi(0, "St_InsertModeSep", { bg = "#b9b2af", fg = "#9c7b9c" })
hi(0, "St_Lsp", { bg = "#dcd5d2", fg = "#5e5f65" })
hi(0, "St_LspHints", { bg = "#dcd5d2", fg = "#a685a6" })
hi(0, "St_LspInfo", { bg = "#dcd5d2", fg = "#6c805c" })
hi(0, "St_LspMsg", { bg = "#dcd5d2", fg = "#6c805c" })
hi(0, "St_NTerminalMode", { bg = "#a9a29f", bold = true, fg = "#e6dfdc" })
hi(0, "St_NTerminalModeSep", { bg = "#b9b2af", fg = "#a9a29f" })
hi(0, "St_NormalMode", { bg = "#5e5f65", bold = true, fg = "#e6dfdc" })
hi(0, "St_NormalModeSep", { bg = "#b9b2af", fg = "#5e5f65" })
hi(0, "St_ReplaceMode", { bg = "#cc836c", bold = true, fg = "#e6dfdc" })
hi(0, "St_ReplaceModeSep", { bg = "#b9b2af", fg = "#cc836c" })
hi(0, "St_SelectMode", { bg = "#5f7d9b", bold = true, fg = "#e6dfdc" })
hi(0, "St_SelectModeSep", { bg = "#b9b2af", fg = "#5f7d9b" })
hi(0, "St_TerminalMode", { bg = "#6c805c", bold = true, fg = "#e6dfdc" })
hi(0, "St_TerminalModeSep", { bg = "#b9b2af", fg = "#6c805c" })
hi(0, "St_VisualMode", { bg = "#75998e", bold = true, fg = "#e6dfdc" })
hi(0, "St_VisualModeSep", { bg = "#b9b2af", fg = "#75998e" })
hi(0, "St_cwd_icon", { bg = "#b28069", fg = "#d0c9c6" })
hi(0, "St_cwd_sep", { bg = "#dcd5d2", fg = "#b28069" })
hi(0, "St_cwd_text", { bg = "#cdc6c3", fg = "#695d57" })
hi(0, "St_file", { bg = "#cdc6c3", fg = "#695d57" })
hi(0, "St_file_sep", { bg = "#dcd5d2", fg = "#cdc6c3" })
hi(0, "St_gitIcons", { bg = "#dcd5d2", bold = true, fg = "#b3adab" })
hi(0, "St_lspError", { bg = "#dcd5d2", fg = "#b28069" })
hi(0, "St_lspWarning", { bg = "#dcd5d2", fg = "#a9a29f" })
hi(0, "St_pos_icon", { bg = "#6c805c", fg = "#e6dfdc" })
hi(0, "St_pos_sep", { bg = "#cdc6c3", fg = "#6c805c" })
hi(0, "St_pos_text", { bg = "#cdc6c3", fg = "#695d57" })
hi(0, "Statement", { fg = "#8779a8" })
hi(0, "StatusLine", { bg = "#dcd5d2" })
hi(0, "StorageClass", { fg = "#738199" })
hi(0, "String", { fg = "#6c805c" })
hi(0, "Structure", { fg = "#7e8e8e" })
hi(0, "Substitute", { bg = "#738199", fg = "#ded7d4" })
hi(0, "TBTabTitle", { bg = "#5f7d9b", fg = "#e6dfdc" })
hi(0, "Tag", { fg = "#738199" })
hi(0, "TbBufOff", { bg = "#d9d2cf", fg = "#a09996" })
hi(0, "TbBufOffClose", { bg = "#d9d2cf", fg = "#a09996" })
hi(0, "TbBufOffModified", { bg = "#d9d2cf", fg = "#b28069" })
hi(0, "TbBufOn", { bg = "#e6dfdc", fg = "#695d57" })
hi(0, "TbBufOnClose", { bg = "#e6dfdc", fg = "#b28069" })
hi(0, "TbBufOnModified", { bg = "#e6dfdc", fg = "#6c805c" })
hi(0, "TbCloseAllBufsBtn", { bg = "#b28069", bold = true, fg = "#e6dfdc" })
hi(0, "TbFill", { bg = "#d9d2cf" })
hi(0, "TbLineThemeToggleBtn", { bg = "#695d57", fg = "#e6dfdc" })
hi(0, "TbTabCloseBtn", { bg = "#5e5f65", fg = "#e6dfdc" })
hi(0, "TbTabNewBtn", { bg = "#c7c0bd", fg = "#695d57" })
hi(0, "TbTabOff", { bg = "#d9d2cf", fg = "#695d57" })
hi(0, "TbTabOn", { fg = "#b28069" })
hi(0, "TbThemeToggleBtn", { bg = "#c0b9b6", bold = true, fg = "#695d57" })
hi(0, "TelescopeBorder", { bg = "#dfd8d5", fg = "#dfd8d5" })
hi(0, "TelescopeMatching", { bg = "#d0c9c6", fg = "#5f7d9b" })
hi(0, "TelescopeNormal", { bg = "#dfd8d5" })
hi(0, "TelescopePreviewTitle", { bg = "#6c805c", fg = "#e6dfdc" })
hi(0, "TelescopePromptBorder", { bg = "#d9d2cf", fg = "#d9d2cf" })
hi(0, "TelescopePromptNormal", { bg = "#d9d2cf", fg = "#695d57" })
hi(0, "TelescopePromptPrefix", { bg = "#d9d2cf", fg = "#b28069" })
hi(0, "TelescopePromptTitle", { bg = "#b28069", fg = "#e6dfdc" })
hi(0, "TelescopeResultsDiffAdd", { fg = "#6c805c" })
hi(0, "TelescopeResultsDiffChange", { fg = "#a9a29f" })
hi(0, "TelescopeResultsDiffDelete", { fg = "#b28069" })
hi(0, "TelescopeResultsTitle", { bg = "#dfd8d5", fg = "#dfd8d5" })
hi(0, "TelescopeSelection", { bg = "#d9d2cf", fg = "#695d57" })
hi(0, "Title", { fg = "#b3816a" })
hi(0, "Todo", { bg = "#ded7d4", fg = "#738199" })
hi(0, "TooLong", { fg = "#8779a8" })
hi(0, "Type", { fg = "#738199" })
hi(0, "Typedef", { fg = "#738199" })
hi(0, "Variable", { fg = "#746862" })
hi(0, "Visual", { bg = "#d7d0cd" })
hi(0, "VisualNOS", { fg = "#8779a8" })
hi(0, "WarningMsg", { fg = "#8779a8" })
hi(0, "WhichKey", { fg = "#695d57" })
hi(0, "WhichKeyDesc", { fg = "#695d57" })
hi(0, "WhichKeyGroup", { fg = "#6c805c" })
hi(0, "WhichKeySeparator", { fg = "#a09996" })
hi(0, "WhichKeyValue", { fg = "#6c805c" })
hi(0, "WildMenu", { bg = "#738199", fg = "#8779a8" })
hi(0, "WinSeparator", { fg = "#d3ccc9" })
hi(0, "diffNewFile", { fg = "#5f7d9b" })
hi(0, "diffOldFile", { fg = "#b7856e" })
hi(0, "gitcommitBranch", { bold = true, fg = "#a87678" })
hi(0, "gitcommitComment", { fg = "#d1cac7" })
hi(0, "gitcommitDiscarded", { fg = "#d1cac7" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#8779a8" })
hi(0, "gitcommitDiscardedType", { fg = "#b3816a" })
hi(0, "gitcommitHeader", { fg = "#7e8e8e" })
hi(0, "gitcommitOverflow", { fg = "#8779a8" })
hi(0, "gitcommitSelected", { fg = "#d1cac7" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#6c805c" })
hi(0, "gitcommitSelectedType", { fg = "#b3816a" })
hi(0, "gitcommitSummary", { fg = "#6c805c" })
hi(0, "gitcommitUnmergedFile", { bold = true, fg = "#8779a8" })
hi(0, "gitcommitUnmergedType", { fg = "#b3816a" })
hi(0, "gitcommitUntracked", { fg = "#d1cac7" })
hi(0, "gitcommitUntrackedFile", { fg = "#738199" })
hi(0, "healthSuccess", { bg = "#6c805c", fg = "#e6dfdc" })
hi(0, "lCursor", { bg = "#bfc6d4", fg = "#1e1d2d" })
hi(0, "luaTSField", { fg = "#fa8d3e" })
hi(0, "parameter", { fg = "#51afef" })

-- No terminal colors defined
