-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "kanagawa-chad"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { fg = "#d8616b" })
hi(0, "@attribute", { fg = "#dca561" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character", { fg = "#d8616b" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment", { fg = "#4c4c55" })
hi(0, "@comment.danger", { bg = "#d8616b", fg = "#25252e" })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { bg = "#dcd7ba", fg = "#25252e" })
hi(0, "@comment.todo", { bg = "#dcd7ba", fg = "#43434c" })
hi(0, "@comment.warning", { bg = "#ffa066", fg = "#25252e" })
hi(0, "@conditional.ternary", { fg = "#89ddff" })
hi(0, "@constant", { fg = "#d8616b" })
hi(0, "@constant.builtin", { fg = "#ffa066" })
hi(0, "@constant.macro", { fg = "#d8616b" })
hi(0, "@constructor", { fg = "#7fb4ca" })
hi(0, "@definition", { sp = "#4c4c55", underline = true })
hi(0, "@delimiter", { fg = "#da70ca" })
hi(0, "@diff.delta", { fg = "#5c5c65" })
hi(0, "@diff.minus", { fg = "#d8616b" })
hi(0, "@diff.plus", { fg = "#98bb6c" })
hi(0, "@error", { fg = "#d8616b" })
hi(0, "@function", { fg = "#7e9cd8" })
hi(0, "@function.builtin", { fg = "#7e9cd8" })
hi(0, "@function.call", { fg = "#7e9cd8" })
hi(0, "@function.macro", { fg = "#d8616b" })
hi(0, "@function.method", { fg = "#7e9cd8" })
hi(0, "@function.method.call", { fg = "#7e9cd8" })
hi(0, "@ibl.indent.char.1", { fg = "#31313a", nocombine = true })
hi(0, "@ibl.scope.char.1", { fg = "#43434c", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#43434c", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = "#363646" })
hi(0, "@keyword", { fg = "#9c86bf" })
hi(0, "@keyword.conditional", { fg = "#9c86bf" })
hi(0, "@keyword.conditional.ternary", { fg = "#9c86bf" })
hi(0, "@keyword.directive", { fg = "#dca561" })
hi(0, "@keyword.directive.define", { fg = "#9c86bf" })
hi(0, "@keyword.exception", { fg = "#d8616b" })
hi(0, "@keyword.function", { fg = "#9c86bf" })
hi(0, "@keyword.import", { fg = "#7e9cd8" })
hi(0, "@keyword.operator", { fg = "#9c86bf" })
hi(0, "@keyword.repeat", { fg = "#dca561" })
hi(0, "@keyword.return", { fg = "#9c86bf" })
hi(0, "@keyword.storage", { fg = "#dca561" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading", { fg = "#7e9cd8" })
hi(0, "@markup.link", { fg = "#d8616b" })
hi(0, "@markup.link.label", { fg = "#7fb4ca" })
hi(0, "@markup.link.url", { fg = "#ffa066", underline = true })
hi(0, "@markup.list", { fg = "#d8616b" })
hi(0, "@markup.quote", { bg = "#25252e" })
hi(0, "@markup.raw", { fg = "#ffa066" })
hi(0, "@module", { fg = "#d8616b" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@number", { fg = "#ffa066" })
hi(0, "@number.float", { fg = "#ffa066" })
hi(0, "@operator", { fg = "#c8c3a6" })
hi(0, "@parenthesis", { link = "@punctuation.bracket" })
hi(0, "@property", { fg = "#d8616b" })
hi(0, "@punctuation.bracket", { fg = "#a48ec7" })
hi(0, "@punctuation.delimiter", { fg = "#dcd7ba" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@reference", { fg = "#c8c3a6" })
hi(0, "@scope", { bold = true })
hi(0, "@string", { fg = "#98bb6c" })
hi(0, "@string.escape", { fg = "#7fb4ca" })
hi(0, "@string.regex", { fg = "#7fb4ca" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { fg = "#879a39" })
hi(0, "@symbol", { fg = "#98bb6c" })
hi(0, "@tag", { fg = "#dca561" })
hi(0, "@tag.attribute", { fg = "#d8616b" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#d8616b" })
hi(0, "@text", { fg = "#c8c3a6" })
hi(0, "@text.emphasis", { fg = "#ffa066" })
hi(0, "@text.strike", { fg = "#d8616b", strikethrough = true })
hi(0, "@type.builtin", { fg = "#dca561" })
hi(0, "@type.qualifier", { fg = "#89ddff" })
hi(0, "@uri", { fg = "#7fb4ca" })
hi(0, "@variable", { fg = "#c8c3a6" })
hi(0, "@variable.builtin", { fg = "#ffa066" })
hi(0, "@variable.member", { fg = "#d8616b" })
hi(0, "@variable.member.key", { fg = "#dcd7ba" })
hi(0, "@variable.parameter", { fg = "#d8616b" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#ffa066" })
hi(0, "Character", { fg = "#d8616b" })
hi(0, "CmpBorder", { fg = "#4c4c55" })
hi(0, "CmpDoc", { bg = "#191922" })
hi(0, "CmpDocBorder", { bg = "#191922", fg = "#191922" })
hi(0, "CmpItemAbbr", { fg = "#dcd7ba" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#565c64" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#7fb4ca" })
hi(0, "CmpItemKindClass", { fg = "#7aa89f" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCodeium", { fg = "#a3c677" })
hi(0, "CmpItemKindColor", { fg = "#dcd7ba" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#ffa066" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#7fb4ca" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#98bb6c" })
hi(0, "CmpItemKindDefault", { fg = "#56b6c2" })
hi(0, "CmpItemKindEnum", { fg = "#7fb4ca" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#a48ec7" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#ff9e3b" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#d8616b" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#dcd7ba" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#dcd7ba" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#7e9cd8" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindIdentifier", { fg = "#d8616b" })
hi(0, "CmpItemKindInterface", { fg = "#98bb6c" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#dcd7ba" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#7e9cd8" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#dca561" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#c8c3a6" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#d8616b" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#c8c3a6" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#d8616b" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#9c86bf" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructure", { fg = "#9c86bf" })
hi(0, "CmpItemKindTabNine", { fg = "#d27e99" })
hi(0, "CmpItemKindText", { fg = "#98bb6c" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindType", { fg = "#dca561" })
hi(0, "CmpItemKindTypeParameter", { fg = "#d8616b" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#9c86bf" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#a3d4d5" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#9c86bf" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpPmenu", { bg = "#1f1f28" })
hi(0, "CmpSel", { bg = "#a48ec7", fg = "#1f1f28" })
hi(0, "ColorColumn", { bg = "#25252e" })
hi(0, "Comment", { fg = "#4c4c55" })
hi(0, "Conceal", {})
hi(0, "Conditional", { fg = "#9c86bf" })
hi(0, "Constant", { fg = "#d8616b" })
hi(0, "Cursor", { bg = "#c8c3a6", fg = "#1f1f28" })
hi(0, "CursorColumn", { bg = "#2a2a37" })
hi(0, "CursorLine", { bg = "#25252e" })
hi(0, "CursorLineNr", { fg = "#dcd7ba" })
hi(0, "Debug", { fg = "#d8616b" })
hi(0, "Define", { fg = "#9c86bf" })
hi(0, "Delimiter", { fg = "#d8616b" })
hi(0, "DiagnosticError", { fg = "#d8616b" })
hi(0, "DiagnosticHint", { fg = "#a48ec7" })
hi(0, "DiagnosticInfo", { fg = "#98bb6c" })
hi(0, "DiagnosticWarn", { fg = "#ff9e3b" })
hi(0, "DiffAdd", { fg = "#7fb4ca" })
hi(0, "DiffAdded", { fg = "#98bb6c" })
hi(0, "DiffChange", { fg = "#5c5c65" })
hi(0, "DiffChangeDelete", { fg = "#d8616b" })
hi(0, "DiffDelete", { fg = "#d8616b" })
hi(0, "DiffModified", { fg = "#fa9b61" })
hi(0, "DiffRemoved", { fg = "#d8616b" })
hi(0, "DiffText", { bg = "#25252e", fg = "#dcd7ba" })
hi(0, "Directory", { fg = "#7e9cd8" })
hi(0, "Error", { bg = "#d8616b", fg = "#1f1f28" })
hi(0, "ErrorMsg", { bg = "#1f1f28", fg = "#d8616b" })
hi(0, "Exception", { fg = "#d8616b" })
hi(0, "Float", { fg = "#ffa066" })
hi(0, "FloatBorder", { fg = "#7fb4ca" })
hi(0, "FoldColumn", { bg = "#2a2a37", fg = "#7fb4ca" })
hi(0, "Folded", { bg = "#25252e", fg = "#5c5c65" })
hi(0, "Function", { fg = "#7e9cd8" })
hi(0, "GitSignsStagedAdd", { fg = "#597b60" })
hi(0, "GitSignsStagedAddLn", { fg = "#305777" })
hi(0, "GitSignsStagedAddNr", { fg = "#597b60" })
hi(0, "GitSignsStagedChange", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangeLn", { fg = "#37393d" })
hi(0, "GitSignsStagedChangeNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedelete", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#37393d" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedDelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7f605c" })
hi(0, "IblChar", { fg = "#31313a" })
hi(0, "IblIndent", { link = "NonText" })
hi(0, "IblScope", { fg = "#42464e" })
hi(0, "IblScopeChar", { fg = "#43434c" })
hi(0, "IblWhitespace", { link = "NonText" })
hi(0, "Identifier", { fg = "#d8616b" })
hi(0, "IncSearch", { bg = "#ffa066", fg = "#2a2a37" })
hi(0, "Include", { fg = "#7e9cd8" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#9c86bf" })
hi(0, "Label", { fg = "#dca561" })
hi(0, "LazyButton", { bg = "#272730", fg = "#74747f" })
hi(0, "LazyCommit", { fg = "#98bb6c" })
hi(0, "LazyCommitIssue", { fg = "#c8748f" })
hi(0, "LazyDir", { fg = "#c8c3a6" })
hi(0, "LazyH1", { bg = "#98bb6c", fg = "#1f1f28" })
hi(0, "LazyH2", { bold = true, fg = "#d8616b", underline = true })
hi(0, "LazyNoCond", { fg = "#d8616b" })
hi(0, "LazyOperator", { fg = "#dcd7ba" })
hi(0, "LazyProgressDone", { fg = "#98bb6c" })
hi(0, "LazyReasonCmd", { fg = "#ffa066" })
hi(0, "LazyReasonEvent", { fg = "#ff9e3b" })
hi(0, "LazyReasonFt", { fg = "#a48ec7" })
hi(0, "LazyReasonImport", { fg = "#dcd7ba" })
hi(0, "LazyReasonKeys", { fg = "#7aa89f" })
hi(0, "LazyReasonPlugin", { fg = "#d8616b" })
hi(0, "LazyReasonRuntime", { fg = "#7e9cd8" })
hi(0, "LazyReasonSource", { fg = "#a3d4d5" })
hi(0, "LazyReasonStart", { fg = "#dcd7ba" })
hi(0, "LazySpecial", { fg = "#7fb4ca" })
hi(0, "LazyTaskOutput", { fg = "#dcd7ba" })
hi(0, "LazyUrl", { fg = "#c8c3a6" })
hi(0, "LazyValue", { fg = "#7aa89f" })
hi(0, "LineNr", { fg = "#43434c" })
hi(0, "LspInlayHint", { bg = "#25252e", fg = "#5c5c65" })
hi(0, "LspReferenceRead", { bg = "#dcd7ba", fg = "#191922" })
hi(0, "LspReferenceText", { bg = "#dcd7ba", fg = "#191922" })
hi(0, "LspReferenceWrite", { bg = "#dcd7ba", fg = "#191922" })
hi(0, "LspSignatureActiveParameter", { bg = "#98bb6c", fg = "#1f1f28" })
hi(0, "Macro", { fg = "#d8616b" })
hi(0, "MasonHeader", { bg = "#d8616b", fg = "#1f1f28" })
hi(0, "MasonHeaderSecondary", { link = "MasonHighlightBlock" })
hi(0, "MasonHighlight", { fg = "#7fb4ca" })
hi(0, "MasonHighlightBlock", { bg = "#98bb6c", fg = "#1f1f28" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHighlightBlock" })
hi(0, "MasonMuted", { fg = "#5c5c65" })
hi(0, "MasonMutedBlock", { bg = "#272730", fg = "#5c5c65" })
hi(0, "MatchParen", { link = "MatchWord" })
hi(0, "MatchWord", { bg = "#43434c", fg = "#dcd7ba" })
hi(0, "ModeMsg", { fg = "#98bb6c" })
hi(0, "MoreMsg", { fg = "#98bb6c" })
hi(0, "NonText", { fg = "#363646" })
hi(0, "Normal", { bg = "#1f1f28", fg = "#c8c3a6" })
hi(0, "NormalFloat", { bg = "#191922" })
hi(0, "Number", { fg = "#d27e99" })
hi(0, "NvChAsciiHeader", { fg = "#7fb4ca" })
hi(0, "NvChHeadbaby_pink", { bg = "#d27e99", fg = "#1f1f28" })
hi(0, "NvChHeadblue", { bg = "#7fb4ca", fg = "#1f1f28" })
hi(0, "NvChHeadcyan", { bg = "#a3d4d5", fg = "#1f1f28" })
hi(0, "NvChHeadgreen", { bg = "#98bb6c", fg = "#1f1f28" })
hi(0, "NvChHeading", { bg = "#7fb4ca", bold = true, fg = "#1f1f28" })
hi(0, "NvChHeadorange", { bg = "#fa9b61", fg = "#1f1f28" })
hi(0, "NvChHeadpurple", { bg = "#a48ec7", fg = "#1f1f28" })
hi(0, "NvChHeadred", { bg = "#d8616b", fg = "#1f1f28" })
hi(0, "NvChHeadteal", { bg = "#7aa89f", fg = "#1f1f28" })
hi(0, "NvChHeadvibrant_green", { bg = "#a3c677", fg = "#1f1f28" })
hi(0, "NvChHeadwhite", { bg = "#dcd7ba", fg = "#1f1f28" })
hi(0, "NvChHeadyellow", { bg = "#ff9e3b", fg = "#1f1f28" })
hi(0, "NvChSection", { bg = "#25252e" })
hi(0, "NvDashAscii", { bg = "#7fb4ca", fg = "#1f1f28" })
hi(0, "NvDashButtons", { bg = "#25252e", fg = "#dcd7ba" })
hi(0, "NvimInternalError", { fg = "#d8616b" })
hi(0, "NvimTreeCursorLine", { bg = "#25252e" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#7e9cd8" })
hi(0, "NvimTreeEndOfBuffer", { fg = "#191922" })
hi(0, "NvimTreeFolderArrowClosed", { fg = "#4c4c55" })
hi(0, "NvimTreeFolderArrowOpen", { fg = "#7e9cd8" })
hi(0, "NvimTreeFolderIcon", { fg = "#7e9cd8" })
hi(0, "NvimTreeFolderName", { fg = "#7e9cd8" })
hi(0, "NvimTreeGitDeleted", { fg = "#d8616b" })
hi(0, "NvimTreeGitDirty", { fg = "#d8616b" })
hi(0, "NvimTreeGitIgnored", { fg = "#5c5c65" })
hi(0, "NvimTreeGitNew", { fg = "#ff9e3b" })
hi(0, "NvimTreeIndentMarker", { fg = "#2c2c34" })
hi(0, "NvimTreeNormal", { bg = "#191922" })
hi(0, "NvimTreeNormalNC", { bg = "#191922" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#7e9cd8" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#d8616b" })
hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#ff9e3b" })
hi(0, "NvimTreeWinSeparator", { bg = "#191922", fg = "#191922" })
hi(0, "NvimTreeWindowPicker", { bg = "#25252e", fg = "#d8616b" })
hi(0, "Operator", { fg = "#c8c3a6" })
hi(0, "Pmenu", { bg = "#272730" })
hi(0, "PmenuSbar", { bg = "#272730" })
hi(0, "PmenuSel", { bg = "#a48ec7", fg = "#1f1f28" })
hi(0, "PmenuThumb", { bg = "#43434c" })
hi(0, "PreProc", { fg = "#dca561" })
hi(0, "Question", { fg = "#7e9cd8" })
hi(0, "QuickFixLine", { bg = "#2a2a37" })
hi(0, "RenamerBorder", { fg = "#d8616b" })
hi(0, "RenamerTitle", { bg = "#d8616b", fg = "#1f1f28" })
hi(0, "Repeat", { fg = "#dca561" })
hi(0, "Search", { bg = "#dca561", fg = "#2a2a37" })
hi(0, "SignColumn", { fg = "#363646" })
hi(0, "Special", { fg = "#7fb4ca" })
hi(0, "SpecialChar", { fg = "#d8616b" })
hi(0, "SpecialKey", { fg = "#363646" })
hi(0, "SpellBad", { sp = "#d8616b", undercurl = true })
hi(0, "SpellCap", { sp = "#7e9cd8", undercurl = true })
hi(0, "SpellLocal", { sp = "#7fb4ca", undercurl = true })
hi(0, "SpellRare", { sp = "#9c86bf", undercurl = true })
hi(0, "St_CommandMode", { bg = "#98bb6c", bold = true, fg = "#1f1f28" })
hi(0, "St_CommandModeSep", { bg = "#43434c", fg = "#98bb6c" })
hi(0, "St_ConfirmMode", { bg = "#7aa89f", bold = true, fg = "#1f1f28" })
hi(0, "St_ConfirmModeSep", { bg = "#43434c", fg = "#7aa89f" })
hi(0, "St_EmptySpace", { bg = "#33333c", fg = "#43434c" })
hi(0, "St_InsertMode", { bg = "#9c86bf", bold = true, fg = "#1f1f28" })
hi(0, "St_InsertModeSep", { bg = "#43434c", fg = "#9c86bf" })
hi(0, "St_Lsp", { bg = "#24242d", fg = "#7e9cd8" })
hi(0, "St_LspHints", { bg = "#24242d", fg = "#a48ec7" })
hi(0, "St_LspInfo", { bg = "#24242d", fg = "#98bb6c" })
hi(0, "St_LspMsg", { bg = "#24242d", fg = "#98bb6c" })
hi(0, "St_NTerminalMode", { bg = "#ff9e3b", bold = true, fg = "#1f1f28" })
hi(0, "St_NTerminalModeSep", { bg = "#43434c", fg = "#ff9e3b" })
hi(0, "St_NormalMode", { bg = "#7e9cd8", bold = true, fg = "#1f1f28" })
hi(0, "St_NormalModeSep", { bg = "#43434c", fg = "#7e9cd8" })
hi(0, "St_ReplaceMode", { bg = "#fa9b61", bold = true, fg = "#1f1f28" })
hi(0, "St_ReplaceModeSep", { bg = "#43434c", fg = "#fa9b61" })
hi(0, "St_SelectMode", { bg = "#7fb4ca", bold = true, fg = "#1f1f28" })
hi(0, "St_SelectModeSep", { bg = "#43434c", fg = "#7fb4ca" })
hi(0, "St_TerminalMode", { bg = "#98bb6c", bold = true, fg = "#1f1f28" })
hi(0, "St_TerminalModeSep", { bg = "#43434c", fg = "#98bb6c" })
hi(0, "St_VisualMode", { bg = "#a3d4d5", bold = true, fg = "#1f1f28" })
hi(0, "St_VisualModeSep", { bg = "#43434c", fg = "#a3d4d5" })
hi(0, "St_cwd_icon", { bg = "#d8616b", fg = "#272730" })
hi(0, "St_cwd_sep", { bg = "#24242d", fg = "#d8616b" })
hi(0, "St_cwd_text", { bg = "#33333c", fg = "#dcd7ba" })
hi(0, "St_file", { bg = "#33333c", fg = "#dcd7ba" })
hi(0, "St_file_sep", { bg = "#24242d", fg = "#33333c" })
hi(0, "St_gitIcons", { bg = "#24242d", bold = true, fg = "#6f6f7a" })
hi(0, "St_lspError", { bg = "#24242d", fg = "#d8616b" })
hi(0, "St_lspWarning", { bg = "#24242d", fg = "#ff9e3b" })
hi(0, "St_pos_icon", { bg = "#98bb6c", fg = "#1f1f28" })
hi(0, "St_pos_sep", { bg = "#33333c", fg = "#98bb6c" })
hi(0, "St_pos_text", { bg = "#33333c", fg = "#98bb6c" })
hi(0, "Statement", { fg = "#d8616b" })
hi(0, "StatusLine", { bg = "#24242d" })
hi(0, "StorageClass", { fg = "#dca561" })
hi(0, "String", { fg = "#98bb6c" })
hi(0, "Structure", { fg = "#9c86bf" })
hi(0, "Substitute", { bg = "#dca561", fg = "#2a2a37" })
hi(0, "TBTabTitle", { bg = "#7fb4ca", fg = "#1f1f28" })
hi(0, "Tag", { fg = "#dca561" })
hi(0, "TbBufOff", { bg = "#25252e", fg = "#5c5c65" })
hi(0, "TbBufOffClose", { bg = "#25252e", fg = "#5c5c65" })
hi(0, "TbBufOffModified", { bg = "#25252e", fg = "#d8616b" })
hi(0, "TbBufOn", { bg = "#1f1f28", fg = "#dcd7ba" })
hi(0, "TbBufOnClose", { bg = "#1f1f28", fg = "#d8616b" })
hi(0, "TbBufOnModified", { bg = "#1f1f28", fg = "#98bb6c" })
hi(0, "TbCloseAllBufsBtn", { bg = "#d8616b", bold = true, fg = "#1f1f28" })
hi(0, "TbFill", { bg = "#25252e" })
hi(0, "TbLineThemeToggleBtn", { bg = "#504945", fg = "#f2e5bc" })
hi(0, "TbTabCloseBtn", { bg = "#7e9cd8", fg = "#1f1f28" })
hi(0, "TbTabNewBtn", { bg = "#2f2f38", fg = "#dcd7ba" })
hi(0, "TbTabOff", { bg = "#25252e", fg = "#dcd7ba" })
hi(0, "TbTabOn", { fg = "#d8616b" })
hi(0, "TbThemeToggleBtn", { bg = "#363646", bold = true, fg = "#dcd7ba" })
hi(0, "TelescopeBorder", { bg = "#191922", fg = "#191922" })
hi(0, "TelescopeMatching", { bg = "#272730", fg = "#7fb4ca" })
hi(0, "TelescopeNormal", { bg = "#191922" })
hi(0, "TelescopePreviewTitle", { bg = "#98bb6c", fg = "#1f1f28" })
hi(0, "TelescopePromptBorder", { bg = "#25252e", fg = "#25252e" })
hi(0, "TelescopePromptNormal", { bg = "#25252e", fg = "#dcd7ba" })
hi(0, "TelescopePromptPrefix", { bg = "#25252e", fg = "#d8616b" })
hi(0, "TelescopePromptTitle", { bg = "#d8616b", fg = "#1f1f28" })
hi(0, "TelescopeResultsDiffAdd", { fg = "#98bb6c" })
hi(0, "TelescopeResultsDiffChange", { fg = "#ff9e3b" })
hi(0, "TelescopeResultsDiffDelete", { fg = "#d8616b" })
hi(0, "TelescopeResultsTitle", { bg = "#191922", fg = "#191922" })
hi(0, "TelescopeSelection", { bg = "#25252e", fg = "#dcd7ba" })
hi(0, "Title", { fg = "#7e9cd8" })
hi(0, "Todo", { bg = "#2a2a37", fg = "#dca561" })
hi(0, "TooLong", { fg = "#d8616b" })
hi(0, "Type", { fg = "#dca561" })
hi(0, "Typedef", { fg = "#dca561" })
hi(0, "Variable", { fg = "#c8c3a6" })
hi(0, "Visual", { bg = "#223249" })
hi(0, "VisualNOS", { fg = "#d8616b" })
hi(0, "WarningMsg", { fg = "#d8616b" })
hi(0, "WhichKey", { fg = "#7fb4ca" })
hi(0, "WhichKeyDesc", { fg = "#d8616b" })
hi(0, "WhichKeyGroup", { fg = "#98bb6c" })
hi(0, "WhichKeySeparator", { fg = "#5c5c65" })
hi(0, "WhichKeyValue", { fg = "#98bb6c" })
hi(0, "WildMenu", { bg = "#dca561", fg = "#d8616b" })
hi(0, "WinSeparator", { fg = "#31313a" })
hi(0, "diffNewFile", { fg = "#7fb4ca" })
hi(0, "diffOldFile", { fg = "#d27e99" })
hi(0, "gitcommitBranch", { bold = true, fg = "#ffa066" })
hi(0, "gitcommitComment", { fg = "#363646" })
hi(0, "gitcommitDiscarded", { fg = "#363646" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#d8616b" })
hi(0, "gitcommitDiscardedType", { fg = "#7e9cd8" })
hi(0, "gitcommitHeader", { fg = "#9c86bf" })
hi(0, "gitcommitOverflow", { fg = "#d8616b" })
hi(0, "gitcommitSelected", { fg = "#363646" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#98bb6c" })
hi(0, "gitcommitSelectedType", { fg = "#7e9cd8" })
hi(0, "gitcommitSummary", { fg = "#98bb6c" })
hi(0, "gitcommitUnmergedFile", { bold = true, fg = "#d8616b" })
hi(0, "gitcommitUnmergedType", { fg = "#7e9cd8" })
hi(0, "gitcommitUntracked", { fg = "#363646" })
hi(0, "gitcommitUntrackedFile", { fg = "#dca561" })
hi(0, "healthSuccess", { bg = "#98bb6c", fg = "#1f1f28" })
hi(0, "lCursor", { bg = "#bfc6d4", fg = "#1e1d2d" })
hi(0, "luaTSField", { fg = "#fa8d3e" })

-- No terminal colors defined
