#!/usr/bin/env bash
#
# Interactively commit changes to the repository.
#
VARIANT="${CI_VARIANT:-2}"

WHITE="\e[0m"
COLOR="\e[3${VARIANT};1m"

GUM_CHOOSE_CURSOR_FOREGROUND="${VARIANT}"
GUM_CHOOSE_SELECTED_FOREGROUND="${VARIANT}"

TYPE=$(gum choose "fix:      A bug fix" "feat:     A new feature" "docs:     Documentation only change" "style:    Changes that do not affect the meaning of the code" "refactor: A code change that neither fixes a bug nor adds a feature" "test:     Adding missing or correcting existing tests" "chore:    Other changes that don't modify src or test files" "build:    Changes that affect the build system or external dependencies" --header="Select the type of change:" --no-show-help)

if [[ -z "${TYPE}" ]]; then
    exit 1
else
    TYPE="$(echo "${TYPE}" | cut -d: -f1)"
fi

echo -e "Select the type of change: ${COLOR}${TYPE}${WHITE}"

#
# Scope
#
SCOPE=$(gum input --prompt="What is the scope of this change? " --placeholder="scope (optional)" --no-show-help)

echo -e "What is the scope of this change: ${COLOR}${SCOPE:--}${WHITE}"

# Since the scope is optional, wrap it in parentheses if it has a value.
test -n "$SCOPE" && SCOPE="($SCOPE)"

#
# Summary
#
SUMMARY=$(gum input --prompt="Write a short summary of the code change: " --placeholder "change summary" --no-show-help)
test -z "${SUMMARY}" && exit 1

echo -e "Write a short summary of the code change: ${COLOR}${SUMMARY}${WHITE}"

confirm() {
    local answer="$(gum choose "Yes" "No" --header="${1}" --no-show-help)"
    [[ "${answer}" = "Yes" ]] && return 0 || return 1
}

#
# Description
#
if confirm "Provide additional information?"; then
    DESCRIPTION=$(gum write --header="Provide additional information about the code changes: " --placeholder "details (optional)")
fi

echo -e "Provide additional information about the code changes: ${COLOR}${DESCRIPTION:--}${WHITE}"

#
# Breaking Change
#
if confirm "Is this a breaking change?"; then
    echo -e "Is this a breaking change: ${COLOR}Yes${WHITE}"
    BREAKING="!"
else
    echo -e "Is this a breaking change: ${COLOR}No${WHITE}"
fi

#
# Commit
#
MESSAGE="${TYPE}${BREAKING}${SCOPE}: ${SUMMARY}"

if [[ -z "${DESCRIPTION}" ]]; then
    git commit -m "${MESSAGE}"
else
    git commit -m "${MESSAGE}" -m "$DESCRIPTION"
fi
