#!/usr/bin/env bash
#
# Edit dotfiles from anywhere
#
dotfiles="${DOTFILES:-${HOME}/dotfiles}"
pushd "${dotfiles}" &> /dev/null || exit 1

file="$(fd --hidden --ignore --type f . | gum filter --placeholder="Select a file")"

[[ -n "${file}" ]] && $EDITOR "${dotfiles}/${file}"
popd &> /dev/null || exit 0
