#!/usr/bin/env bash
#
# Add files to git interactively
#
git_root="$(git rev-parse --show-toplevel)"

candidates="$(git ls-files -mo --exclude-standard --full-name)"
[[ -z "${candidates}" ]] && echo 'No more changes to stage' && exit 0

echo "${candidates}" \
    | tr ' ' '\n' \
    | gum filter --no-limit --fuzzy --placeholder="Select files to stage" \
    | sed -e "s!^!${git_root}/!" \
    | xargs git add
