#!/usr/bin/env bash
#
# Switch git branches interactively
#
branch="$(git branch --sort='-committerdate' --format='%(refname:short)' \
    | gum filter --placeholder='Select branches' \
    | tr -d '\n')"

[[ -z "${branch}" ]] && exit 1

git switch "${branch}"
