#!/usr/bin/env bash
#
# Restore files interactively
#
git_root="$(git-root)"

pushd "${git_root}" > /dev/null

candidates="$(git ls-files -mo --exclude-standard --full-name)"
[[ -z "${candidates}" ]] && echo 'No more changes to restore' && exit 0

echo "${candidates}" \
    | tr ' ' '\n' \
    | gum filter --no-limit --fuzzy --placeholder="Files to restore" \
    | sed -e "s!^!${git_root}/!" \
    | xargs git restore
