#!/usr/bin/env bash
#
# Interactive git commit hash
#
git_root="$(git rev-parse --show-toplevel)"

candidates="$(git log -n "${1:-20}" --pretty=format:"%h [%an] %s")"
[[ -z "${candidates}" ]] && echo 'No commit selected' && exit 1

echo "${candidates}" \
    | gum filter --limit=1 --fuzzy --placeholder="Select a commit" \
    | cut -d ' ' -f 1
