#!/usr/bin/env bash
#
# Unstage files interactively
#
git_root="$(git-root)"

pushd "${git_root}" > /dev/null

candidates="$(git diff --cached --name-only)"
[[ -z "${candidates}" ]] && echo 'No more changes to unstage' && exit 0

echo "${candidates}" \
    | tr ' ' '\n' \
    | gum filter --no-limit --fuzzy --placeholder="Files to unstage" \
    | sed -e "s!^!${git_root}/!" \
    | xargs git restore --staged
