#!/usr/bin/env bash
#
# Interactive git commit hash
#
candidates="$(git log -n "${1:-20}" --color="always" \
    --pretty=format:"%C(yellow)%h %C(auto)[%C(black)%cs%C(auto)] %C(brightblue)%an %C(auto)%<(100,trunc)%s")"

[[ -z "${candidates}" ]] && echo 'No commit selected' && exit 1

echo "${candidates}" \
    | gum filter --limit=1 --fuzzy --placeholder="Select a commit" \
    | cut -d ' ' -f 1
