#!/usr/bin/env bash
#
# Add items to .gitignore with ease
#
git_root="$(git rev-parse --show-toplevel)"

for item in ${*}; do
    echo "${item}" >> "${git_root}/.gitignore"; done

echo "${#} item(s) added to .gitignore"
