#!/usr/bin/env bash
#
# Set neovim colorscheme globally
#
NVIM_DIR="${HOME}/.config/nvim"

colorscheme="$(ls "${NVIM_DIR}/colors" | gum filter)"
[[ -z "${colorscheme}" ]] && exit 1

echo "${colorscheme%.lua}" > "${NVIM_DIR}/colorscheme"
