#!/usr/bin/env zsh
# Author: Alexis Moins
# Creation: 17 oct 2021
# vim: ft=zsh syn=zsh

if [[ -n "${TMUX}" ]]; then
    echo "Unable to restore tmux session"
    echo "=> Already in a tmux session"
    return 1
elif [[ ! -f "${SESSIONFILE}" ]]; then
    echo "Unable to restore tmux session"
    echo "=> Session file ${SESSIONFILE} missing"
    return 1
fi

# Deserializes the given session information.
#
# param {1} the name of session
# param {2} the name of the window
# param {3} the directory of the window
#
deserialize-session() {
    tmux has-session -t "${1}" 2>/dev/null && \
        tmux new-window -d -t "${1}" -n "${2}" -c "${3}" && return 0
    tmux new-session -d -c "${3}" -s "${1}" -n "${2}"
}

# Starts the server if not up already
tmux start-server

# Reads the sessions file and decides how to proceed with the
# retrieved information.
IFS=$'\t'

while read session window dir; do
    [[ -d "${dir}" ]] && deserialize-session "${session}" "${window}" "${dir}"
done < "${SESSIONFILE}"

tmux attach
