#!/usr/bin/env bash
#
# Interactive editor wrapper
#
if [[ -n "${@}" ]]; then
    command "${EDITOR:-vim}" ${@}
else
    # No arguments? Find files to open
    candidates="$(fd --hidden --ignore | gum filter --no-limit --placeholder="Select elements...")"

    command "${EDITOR:-vim}" ${candidates}
fi
