#!/usr/bin/env zsh
# Author: Alexis Moins
# Creation: 18 jan 2022

# Exit with an error if you receive less than 1 argument
[[ "${#}" -lt 1 ]] && echo "usage: ${0:t} user/repo" && exit 1

# Where are all the plugins installed ?
directory="${VIMDOTDIR:-${HOME}/.vim}/pack/bundle/start"

# Create that directory if needed
[[ ! -d "${directory}" ]] && mkdir -pv "${directory}"

# Where will the plugin be installed ?
destination="${directory}/${1##*\/}"

purple='\e[0;35m'

green='\e[0;32m'

default='\e[0m'

# Exit with success if the plugin is already there
[[ -d "${destination}" ]] && echo "Vim plugin exists: ${purple}${1}${default}" && exit 0

repository="${1}"

shift

[[ -d "${repository}" ]] && ln -s "${repository}" "${directory}" && echo "Vim plugin added: ${green}${repository}${default}" && exit 0

# Install the plugin
command git clone --quiet ${*} "https://github.com/${repository}.git" "${destination}"

red='\e[0;31m'

[[ ! -d "${destination}" ]] && echo "Unable to clone plugin: ${red}${repository}${default}" && exit 1


echo "Vim plugin added: ${green}${repository}${default}"

# Clean the environment
unset directory destination repository 

unset red green purple default
